//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRDemo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;



   
    public partial class Employee
    {
        
        [Required]
        public int empid { get; set; }
        [Required]
        [Display(Name ="FullName")]
        public string name { get; set; }
        [Required]
        public string city { get; set; }
        [Required]
        public string address { get; set; }
        [Required]
        [Display(Name = "Department")]
        public int deptid { get; set; }
        public virtual Department Department { get; set; }
    }

   
}
